hkapi:
  #对接秘钥AK
  ak: 26220103
  #SK
  sk: 2GX0ofScLAYbP5zyZW3g
# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 4.2.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: E:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  100MB
       # 设置总上传的文件大小
       max-request-size:  200MB
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 3000
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /system/work
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 300
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

#微信小程序
wx:
  appId: wx7e3a16f20ba86656
  appSecret: 3415df67de1ac289bff132a42356be67
  token:
  aesKey:
  msgDataFormat: JSON

#移动短信
sms:
  template:
    supervisionEvent: xxxxxx    #事件督办短信模板
    illegallyPark:  yyyyyy      #违停短信模板
  url:  http://112.35.1.155:1992/sms/
  apId:       #接口账号
  ecName:     #企业名称
  sign:       #签名编码
  secretKey:  #密钥


img:
  show-url:
  path:
  upload-url: /data/process/

  file-url: http://localhost:9090/img
  event-img-path: /data/img/
  event-video-path: /data/video/

token:
  plat:
    zhzl: 68dbfbb53f3a4d9a8536dce5ce23f14f-platone  #综合治理
    cgsj: d00b69c0262e46dcaa2cb48479085540-plattwo  #城管
    yjxf: 34bc54e4dfe944aab38b9cde69ae434a-platthree  #应急消防
    qsy:  0ff6157702a6424397e2b15764a9c81e-platfour  #青山云
    xlj:  aae1a78c1aca493495fac0f25cf2f0a5-platfive  #新临居


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*,/appwork/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/appwork/*


# 外网文件请求域名替换
replace:
  origin-url:
    #part1: https://qswspro.oss-cn-hangzhou.aliyuncs.com/ #青山云文件域名
    #part2: https://hsh-iot.com/         #应急消防文件域名
    part3: http://172.16.100.15/oss/    #综治文件地址
    part4: https://192.170.1.70:443/    #城管文件地址
    part5: http://172.16.100.13/        #应急文件地址
  target-url:
    #part1: http://172.16.100.10:8082/qsy/   #替换转发ip(青山云文件)
    #part2: http://172.16.100.10:8082/yj/    #替换转发ip(应急消防文件)
    part3: https://qhz.hhkj1688.cn:8389/file-zz/  #浙政钉用综治文件地址
    part4: https://qhz.hhkj1688.cn:8389/file-cg/  #浙政钉用城管文件地址
    part5: https://qhz.hhkj1688.cn:8389/file-yj/  #浙政钉用应急文件地址

#浙政钉用户密码登录
jwt:
  # 请求头携带参数key
  header: Authorization
  #过期时间 单位秒
  expire : 7200
  secret : cD2RUWBkPgJUN&80a28U#5La$#i6YIRq
  #设置缓存前缀
  cache-prefix: ding:user:jwtToken-

#浙政钉接口相关
gov-ding:
  domainName: openplatform-pro.ding.zj.gov.cn
  appkey: qingshanhujiedao_0001-1arEFBfy
  appSecret: W6x9x7IPV583brq6uz134zDJc9Y714N0AP2U9838
  accessTokenPrefix: ding:api:accessToken-   #接口鉴权凭证
  jsApiTicketPrefix: ding:jsapi:ticket-   #jsapi鉴权票据


#浙政钉资料库
file-base:
  #  upload-path: D:\\uploadPath\\
#  upload-path: /home/ma/webapps/img/
  #正式服务器
  upload-path: /home/apache-tomcat-8.5.57/webapps/img/
  #  url-prefix: http://localhost/img/
  #  url-prefix: https://qhz.hhkj1688.cn:8389/file-fk/ding_file/
#  url-prefix: http://139.224.226.216:8383/img/
  #正式服务器
  url-prefix: http://183.134.220.227:58084/img/

#浙政钉事件反馈图片存储,图片存储在服务端主机.为了转换成https.故通过客户端主机映射过来.
event-feedback:
#  upload-path: /home/ma/webapps/img/
  #  upload-path: D:\\uploadPath\\
  #  url-prefix: https://qhz.hhkj1688.cn:8389/file-fk/ding_img/
  #  url-prefix: http://localhost/img/
#  url-prefix: http://139.224.226.216:8383/img/
  #正式服务器
  upload-path: /home/apache-tomcat-8.5.57/webapps/img/
  #正式服务器
  url-prefix: http://183.134.220.227:58084/img/


#流程档案存储位置配置
process-document:
  upload-path: /data/fk_file/
  #  upload-path: D:\\root\\
  url-prefix: https://qhz.hhkj1688.cn:8389/file-fk/fk_file/

platform:
  cg:
    url: http://172.16.100.200:8899/event/dataPush
    eventType:
      motorVehicle: 62040        #机动车违停
  zz:
    url:

hk-video:
    appKey: 27068535
    appSecret: j4jyrStk4KHcWtGg31nZ
    host: 192.170.1.70
    previewUrl: /artemis/api/video/v1/cameras/previewURLs
    playbackUrl: /artemis/api/video/v1/cameras/playbackURLs
#违停
illegallypark:
  appKey: b720c669f14e4ca6ab9a06423b64d952
  appSecret: ec167a1253734ff9b83b1a9792136044
  listurl: http://10.32.188.81:81/gateway/prod/1071/1223
  deailurl: http://10.32.188.81:81/gateway/prod/1072/1241
  imageUrl: http://115.236.6.72:8083/img/sjcg/
#企业
enterprise:
  ak: 15a1ba7b44ae4d7bab68dd698884c71a
  sk: a7baf46335514637b5b3b1a5c5a87c46
  listurl: http://10.32.188.81:81/gateway/prod/1066/1214
  detailurl: http://10.32.188.81:81/gateway/prod/1066/1215
  interval: 0 0 1 * * ?
#统一地址库
address:
  #open是否定时去拉取,0-否,1-是
  #interval间隔时间,单位：小时
  open: 1
  interval: 0 0 0/2 * * ?

  #统一地址账号密码信息（遗弃）
  user: paxf
  pwd: 123
gateway:
  user: xljdjsc
  pwd: 123
  ak: 71698ff10db248909f2e036bee210c09
  sk: ffbf9fdc494c46f7a5bfe22f981420f1
  tokenUrl: http://10.32.188.81:81/gateway/prod/952/876
  addressUrl: http://10.32.188.81:81/gateway/prod/952/877
#垃圾车定位
garbage:
  ak: a981ca54216d4f9c9a84e4bb846794b9
  sk: 96eb6e4843224730a0b27536c795d749
  gpsUrl: http://39.170.15.196:30502/access/bridge/108/push/location
  cheng: http://183.134.103.76:81/api/zs/access/bridge/108/push/weight
#洒水车
jt808:
  enabled: true
  use: mina
  protocol: tcp
  port: 18801
  processCount: 2
  corePoolSize: 1
  maximumPoolSize: 10
  # 单位毫秒
  keepAliveTime: 1000
  # 单位秒
  idleTime: 10
  idleCount: 6
  readBufferSize: 2048
  packageLength: 1024
  threadCorePoolSize: 1
  threadMaximumPoolSize: 10
  # 单位毫秒
  threadKeepAliveTime: 1000
  masterSize: 1
  slaveSize: 10
  tcpNoDelay: true
  keepAlive: true
  auth: false
  authMsgId: "0x0200"
#配置web页面入口
magic-api:
  web: /magic/web
  #配置文件存储位置。当以classpath开头时，为只读模式
  resource:
    type: database
    location: /data/magic-api
